# version: "3.8"

services:
  db:
    container_name: db
    build:
      context: ./Database_Server
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - backend-network

  integration-server:
    container_name: Integration_Server
    networks:
      - backend-network
    cap_add:
      - NET_ADMIN        # 네트워크 관리자 권한 추가
    devices:

      - /dev/net/tun     # TUN 장치가 컨테이너에서 접근할 수 있도록 추가
    volumes:
      - /dev/net/tun:/dev/net/tun  # 호스트와 컨테이너 간 TUN 장치 연결
    build:
      context: ./Integration_Server
      dockerfile: Dockerfile
    command: sh -c "python3 /app/database_initialize.py --password=defaultpassword"
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"

  analytics-server:
    container_name: analytics-server
    networks:
      - backend-network
    build:
      context: ./Analytics_AI
      dockerfile: Dockerfile
    depends_on:
      - db
      - integration-server
    restart: always

networks:
  backend-network:
    driver: bridge
